version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-fer-v2"
s3_bucket = "aws-sam-fer-v2-s3"
s3_prefix = "aws-sam-fer-v2"
region = "eu-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["InferenceFunction=242870391042.dkr.ecr.eu-south-1.amazonaws.com/ferclassifier"]
resolve_s3 = true
